//! Turning a [`Config`] into the Lua that goes inside the managed block.

use crate::block;
use crate::error::Result;
use crate::model::{
    lua_quote, trim_float, Action, Config, LoadMode, ShaderRef, Tag, TagValue, WindowRule,
};

/// The Lua local the generated code binds the shader directory to.
const DIR_VAR: &str = "hws_shaders";
/// The Lua local the generated code binds the plugin table to.
const NS_VAR: &str = "hws";

/// Render the body of the managed block.
///
/// The result does not include the marker lines; pass it to
/// [`crate::block::splice`].
pub fn emit(config: &Config) -> Result<String> {
    let mut out = String::new();
    let stamp = chrono::Local::now().format("%Y-%m-%d %H:%M:%S %:z");

    out.push_str(&format!(
        "-- Generated by hyprwindowshade-gui {} on {stamp}.\n",
        env!("CARGO_PKG_VERSION")
    ));
    out.push_str("-- Edits inside this block are replaced the next time the app saves.\n");
    out.push_str("-- To take this over by hand, delete the two marker lines.\n");
    out.push_str(&block::state_line(config)?);
    out.push('\n');

    let ctx = Ctx::new(config);
    if ctx.use_var {
        out.push('\n');
        out.push_str(&format!("local {DIR_VAR} = {}\n", lua_quote(ctx.dir.trim_end_matches('/'))));
    }

    emit_rules(&mut out, config, &ctx);
    emit_startup(&mut out, config, &ctx);
    emit_binds(&mut out, config, &ctx);

    Ok(out)
}

/// Everything the emitter needs to render a shader path.
struct Ctx {
    dir: String,
    use_var: bool,
}

impl Ctx {
    fn new(config: &Config) -> Self {
        let dir = config.shader_dir.trim_end_matches('/').to_string();
        let use_var = config.use_shader_dir_variable && !dir.is_empty();
        Self { dir, use_var }
    }

    /// The part of a path that lives under the shader directory, if any.
    fn relative(&self, value: &str) -> Option<String> {
        if !self.use_var {
            return None;
        }
        value.strip_prefix(&format!("{}/", self.dir)).map(|rest| format!("/{rest}"))
    }

    /// A Lua expression for a shader path: either `hws_shaders .. "/x.glsl"`
    /// or a plain quoted literal for a path outside the shader directory.
    fn path_expr(&self, value: &str) -> String {
        match self.relative(value) {
            Some(rest) => format!("{DIR_VAR} .. {}", lua_quote(&rest)),
            None => lua_quote(value),
        }
    }

    /// The same, prefixed by a tag key: `"+shader:" .. hws_shaders .. "/x.glsl"`.
    fn tag_expr(&self, tag: &Tag) -> String {
        match &tag.value {
            TagValue::Path(r) => {
                let key = if tag.is_default && tag.slot.info().supports_default {
                    format!("{}_default", tag.slot.key())
                } else {
                    tag.slot.key().to_string()
                };
                let value = r.to_value();
                match self.relative(&value) {
                    // Under the shader directory: concatenate, so the path is
                    // written once at the top of the block.
                    Some(rest) => format!(
                        "{} .. {DIR_VAR} .. {}",
                        lua_quote(&format!("+{key}:")),
                        lua_quote(&rest)
                    ),
                    // Elsewhere: one plain string is easier to read than a
                    // concatenation of two literals.
                    None => lua_quote(&format!("+{key}:{value}")),
                }
            }
            TagValue::Flag { .. } => lua_quote(&tag.to_tag_string()),
        }
    }

    /// A shader argument for a plugin call.
    fn arg_expr(&self, shader: Option<&ShaderRef>) -> String {
        match shader {
            Some(s) => self.path_expr(&s.to_value()),
            None => lua_quote("clear"),
        }
    }
}

// ---------------------------------------------------------------------------
// Window rules
// ---------------------------------------------------------------------------

fn emit_rules(out: &mut String, config: &Config, ctx: &Ctx) {
    let active: Vec<&WindowRule> =
        config.rules.iter().filter(|r| r.enabled && !r.tags.is_empty()).collect();
    if active.is_empty() {
        return;
    }

    out.push_str(
        "\n-- Window rules ------------------------------------------------------------\n",
    );

    for rule in active {
        // Hyprland's Lua window_rule takes one tag per call, so a rule carrying
        // several tags becomes several calls sharing a match. They stack, which
        // is the documented behaviour.
        let multi = rule.tags.len() > 1;
        for tag in &rule.tags {
            out.push('\n');
            out.push_str("hl.window_rule({\n");

            let name = rule_name(rule, tag, multi);
            if !name.is_empty() {
                out.push_str(&format!("    name  = {},\n", lua_quote(&name)));
            }
            out.push_str(&format!("    match = {{ {} }},\n", match_fields(rule)));
            out.push_str(&format!("    tag   = {},\n", ctx.tag_expr(tag)));
            out.push_str("})\n");
        }
    }
}

fn rule_name(rule: &WindowRule, tag: &Tag, multi: bool) -> String {
    let base = if rule.name.trim().is_empty() {
        format!("hws-{}", rule.id)
    } else {
        rule.name.trim().to_string()
    };
    if multi {
        // A rule carrying several tags becomes several calls, so each needs its
        // own name. `shader` has nothing to strip and reads better as "-base".
        // A slot appears at most once per rule, so these stay unique.
        format!("{base}-{}", tag.slot.key().strip_prefix("shader_").unwrap_or("base"))
    } else {
        base
    }
}

fn match_fields(rule: &WindowRule) -> String {
    let m = &rule.match_;
    let mut parts = Vec::new();
    if let Some(v) = &m.class {
        parts.push(format!("class = {}", lua_quote(v)));
    }
    if let Some(v) = &m.title {
        parts.push(format!("title = {}", lua_quote(v)));
    }
    if let Some(v) = &m.initial_class {
        parts.push(format!("initialClass = {}", lua_quote(v)));
    }
    if let Some(v) = &m.initial_title {
        parts.push(format!("initialTitle = {}", lua_quote(v)));
    }
    if parts.is_empty() {
        // An empty match table would match nothing useful; `.*` is the
        // documented catch-all.
        parts.push(format!("class = {}", lua_quote(".*")));
    }
    parts.join(", ")
}

// ---------------------------------------------------------------------------
// Startup: plugin load, layer shaders, class shaders
// ---------------------------------------------------------------------------

fn emit_startup(out: &mut String, config: &Config, ctx: &Ctx) {
    let calls = startup_calls(config, ctx);
    let loader = load_line(config);

    if calls.is_empty() && loader.is_none() {
        return;
    }

    out.push_str(
        "\n-- Session start -----------------------------------------------------------\n\n",
    );
    out.push_str("hl.on(\"hyprland.start\", function()\n");

    if let Some(line) = &loader {
        out.push_str(&format!("    {line}\n"));
        if !calls.is_empty() {
            out.push('\n');
        }
    }

    if !calls.is_empty() {
        if config.startup_delay_secs > 0.0 {
            // Each dispatched expression is evaluated in a fresh Lua context
            // where this file's locals do not exist, so `hws_shaders` would be
            // nil there. Re-render those calls with the paths written out.
            let literal = Ctx { dir: ctx.dir.clone(), use_var: false };
            emit_delayed(out, config, &startup_calls(config, &literal));
        } else {
            out.push_str(&format!("    local {NS_VAR} = hl.plugin.HyprWindowShade\n"));
            out.push_str(&format!("    if not {NS_VAR} then\n"));
            out.push_str("        hl.notification.create({\n");
            out.push_str("            text    = \"[HyprWindowShade] plugin not loaded; shaders not applied\",\n");
            out.push_str("            timeout = 5000,\n");
            out.push_str("            color   = \"rgb(fb4934)\",\n");
            out.push_str("        })\n");
            out.push_str("        return\n");
            out.push_str("    end\n");
            for call in &calls {
                out.push_str(&format!("    {call}\n"));
            }
        }
    }

    out.push_str("end)\n");
}

/// Re-issue the startup calls through a delayed `hyprctl dispatch`.
///
/// `hyprctl dispatch` evaluates its argument as Lua, so the same calls work
/// from a shell. It reports failure after succeeding — see the plugin README —
/// so output and exit status are discarded.
fn emit_delayed(out: &mut String, config: &Config, calls: &[String]) {
    let delay = trim_float(config.startup_delay_secs);
    out.push_str(&format!(
        "    -- Applied {delay}s late so a slow plugin load has finished first.\n"
    ));
    out.push_str("    -- hyprctl dispatch evaluates Lua, and reports failure even when it\n");
    out.push_str("    -- worked, so its output and exit status are discarded on purpose.\n");

    let script = calls
        .iter()
        .map(|c| {
            let expr = c.replacen(&format!("{NS_VAR}."), "hl.plugin.HyprWindowShade.", 1);
            format!("hyprctl dispatch {} >/dev/null 2>&1", shell_single_quote(&expr))
        })
        .collect::<Vec<_>>()
        .join("; ");

    let inner = format!("sleep {delay}; {script}");
    out.push_str(&format!(
        "    hl.exec_cmd({})\n",
        lua_quote(&format!("sh -c {}", shell_single_quote(&inner)))
    ));
}

/// Every plugin call the session-start handler makes, layers first.
///
/// Rendered against a caller-supplied [`Ctx`] because the delayed variant needs
/// the same calls with full paths rather than the directory variable.
fn startup_calls(config: &Config, ctx: &Ctx) -> Vec<String> {
    let actions = config
        .startup
        .iter()
        .filter(|s| s.enabled)
        // Routed through the same renderer the keybinds use, so a startup
        // shader path also goes through the directory variable.
        .map(|s| plugin_call(&s.action, ctx));
    layer_calls(config, ctx).into_iter().chain(actions).collect()
}

fn layer_calls(config: &Config, ctx: &Ctx) -> Vec<String> {
    let mut calls = Vec::new();
    for layer in config.layers.iter().filter(|l| l.enabled && !l.is_empty()) {
        let ns = lua_quote(&layer.namespace);
        if let Some(s) = &layer.shader {
            calls.push(format!("{NS_VAR}.layershader({ns}, {})", ctx.arg_expr(Some(s))));
        }
        if let Some(s) = &layer.open_anim {
            calls.push(format!("{NS_VAR}.layeropenanim({ns}, {})", ctx.arg_expr(Some(s))));
        }
        if let Some(s) = &layer.close_anim {
            calls.push(format!("{NS_VAR}.layercloseanim({ns}, {})", ctx.arg_expr(Some(s))));
        }
    }
    calls
}

fn load_line(config: &Config) -> Option<String> {
    match config.load_mode {
        LoadMode::None => None,
        LoadMode::Hyprpm => Some("hl.exec_cmd(\"hyprpm reload -n\")".to_string()),
        LoadMode::Manual => {
            let p = config.plugin_so_path.trim();
            if p.is_empty() {
                None
            } else {
                Some(format!("hl.exec_cmd({})", lua_quote(&format!("hyprctl plugin load {p}"))))
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Keybinds
// ---------------------------------------------------------------------------

fn emit_binds(out: &mut String, config: &Config, ctx: &Ctx) {
    let binds: Vec<_> =
        config.binds.iter().filter(|b| b.enabled && !b.key.trim().is_empty()).collect();
    if binds.is_empty() {
        return;
    }

    out.push_str(
        "\n-- Keybinds ----------------------------------------------------------------\n",
    );
    out.push_str("--\n");
    out.push_str("-- The plugin table is looked up inside the closure, not at parse time: the\n");
    out.push_str("-- plugin loads at session start, long after this file is read.\n");

    for bind in binds {
        out.push('\n');
        out.push_str(&format!("hl.bind({}, function()\n", lua_quote(bind.key.trim())));
        out.push_str(&format!("    local {NS_VAR} = hl.plugin.HyprWindowShade\n"));
        out.push_str(&format!("    if not {NS_VAR} then\n"));
        out.push_str("        hl.notification.create({\n");
        out.push_str("            text    = \"[HyprWindowShade] plugin not loaded\",\n");
        out.push_str("            timeout = 3000,\n");
        out.push_str("            color   = \"rgb(fb4934)\",\n");
        out.push_str("        })\n");
        out.push_str("        return\n");
        out.push_str("    end\n");
        out.push_str(&format!("    {}\n", plugin_call(&bind.action, ctx)));
        out.push_str("end)\n");
    }
}

/// Like [`Action::to_lua_call`] but routing shader paths through the directory
/// variable.
fn plugin_call(action: &Action, ctx: &Ctx) -> String {
    let q = lua_quote;
    match action {
        Action::ToggleWindowShader { shader } => {
            format!("{NS_VAR}.togglewindowshader({})", ctx.arg_expr(Some(shader)))
        }
        Action::ClassShader { class, shader } => {
            format!("{NS_VAR}.classshader({}, {})", q(class), ctx.arg_expr(shader.as_ref()))
        }
        Action::ToggleClassShader { class, shader } => {
            format!("{NS_VAR}.toggleclassshader({}, {})", q(class), ctx.arg_expr(Some(shader)))
        }
        Action::LayerShader { namespace, shader } => {
            format!("{NS_VAR}.layershader({}, {})", q(namespace), ctx.arg_expr(shader.as_ref()))
        }
        Action::ToggleLayerShader { namespace, shader } => {
            format!("{NS_VAR}.togglelayershader({}, {})", q(namespace), ctx.arg_expr(Some(shader)))
        }
        Action::ReloadShaders => format!("{NS_VAR}.reloadshaders()"),
    }
}

/// Wrap a string in single quotes for `sh -c`, escaping embedded quotes.
fn shell_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Bind, LayerEntry, Match, StartupAction, TagSlot, WindowRule};

    fn cfg() -> Config {
        let mut c = Config::default();
        c.shader_dir = "/home/u/.config/hypr/shaders".into();
        c
    }

    #[test]
    fn rule_uses_the_directory_variable() {
        let mut c = cfg();
        let mut r = WindowRule::new("r1");
        r.name = "kitty-dim".into();
        r.match_ = Match { class: Some("kitty".into()), ..Default::default() };
        r.set_tag(
            Some(Tag {
                slot: TagSlot::Shader,
                is_default: false,
                value: TagValue::Path(ShaderRef::new("/home/u/.config/hypr/shaders/dim.glsl")),
            }),
            TagSlot::Shader,
        );
        c.rules.push(r);

        let out = emit(&c).unwrap();
        assert!(out.contains(r#"local hws_shaders = "/home/u/.config/hypr/shaders""#));
        assert!(out.contains(r#"name  = "kitty-dim""#));
        assert!(out.contains(r#"match = { class = "kitty" }"#));
        assert!(out.contains(r#"tag   = "+shader:" .. hws_shaders .. "/dim.glsl""#));
    }

    #[test]
    fn a_path_outside_the_shader_dir_is_written_in_full() {
        let mut c = cfg();
        let mut r = WindowRule::new("r1");
        r.match_ = Match { class: Some("kitty".into()), ..Default::default() };
        r.set_tag(
            Some(Tag {
                slot: TagSlot::Shader,
                is_default: false,
                value: TagValue::Path(ShaderRef::new("/opt/shaders/x.glsl")),
            }),
            TagSlot::Shader,
        );
        c.rules.push(r);
        let out = emit(&c).unwrap();
        assert!(out.contains(r#"tag   = "+shader:/opt/shaders/x.glsl""#));
    }

    #[test]
    fn several_tags_become_several_rules() {
        let mut c = cfg();
        let mut r = WindowRule::new("r1");
        r.name = "chrome".into();
        r.match_ = Match { class: Some("google-chrome".into()), ..Default::default() };
        r.set_tag(
            Some(Tag {
                slot: TagSlot::Shader,
                is_default: false,
                value: TagValue::Path(ShaderRef::new("/home/u/.config/hypr/shaders/read.glsl")),
            }),
            TagSlot::Shader,
        );
        r.set_tag(
            Some(Tag {
                slot: TagSlot::Inactive,
                is_default: false,
                value: TagValue::Path(ShaderRef::new("/home/u/.config/hypr/shaders/crt.glsl")),
            }),
            TagSlot::Inactive,
        );
        c.rules.push(r);

        let out = emit(&c).unwrap();
        assert_eq!(out.matches("hl.window_rule({").count(), 2);
        assert!(out.contains(r#"name  = "chrome-base""#));
        assert!(out.contains(r#"name  = "chrome-inactive""#));
    }

    #[test]
    fn disabled_things_are_not_emitted() {
        let mut c = cfg();
        let mut r = WindowRule::new("r1");
        r.enabled = false;
        r.set_tag(
            Some(Tag {
                slot: TagSlot::Shader,
                is_default: false,
                value: TagValue::Path(ShaderRef::new("/x.glsl")),
            }),
            TagSlot::Shader,
        );
        c.rules.push(r);
        let out = emit(&c).unwrap();
        assert!(!out.contains("hl.window_rule"));
    }

    #[test]
    fn layers_go_into_a_start_handler() {
        let mut c = cfg();
        let mut l = LayerEntry::new("l1", "rofi");
        l.shader = Some(ShaderRef::new("/home/u/.config/hypr/shaders/blur.glsl"));
        l.open_anim = Some(ShaderRef {
            path: "/home/u/.config/hypr/shaders/open.glsl".into(),
            duration: Some(0.2),
        });
        c.layers.push(l);

        let out = emit(&c).unwrap();
        assert!(out.contains("hl.on(\"hyprland.start\", function()"));
        assert!(out.contains(r#"hws.layershader("rofi", hws_shaders .. "/blur.glsl")"#));
        assert!(out.contains(r#"hws.layeropenanim("rofi", hws_shaders .. "/open.glsl@0.2")"#));
        assert!(out.contains("if not hws then"));
    }

    #[test]
    fn a_startup_delay_switches_to_hyprctl() {
        let mut c = cfg();
        c.startup_delay_secs = 1.5;
        let mut l = LayerEntry::new("l1", "rofi");
        l.shader = Some(ShaderRef::new("/home/u/.config/hypr/shaders/blur.glsl"));
        c.layers.push(l);

        let out = emit(&c).unwrap();
        assert!(out.contains("sleep 1.5"));
        assert!(out.contains("hl.plugin.HyprWindowShade.layershader"));
        assert!(out.contains(">/dev/null 2>&1"));
    }

    #[test]
    fn a_delayed_call_does_not_reference_the_lua_local() {
        // hyprctl dispatch evaluates each expression on its own, in a context
        // where this file's locals do not exist. Referring to hws_shaders there
        // fails with "attempt to concatenate a nil value" — and because the
        // dispatch discards its output, it fails silently.
        let mut c = cfg();
        c.startup_delay_secs = 1.5;
        let mut l = LayerEntry::new("l1", "rofi");
        l.shader = Some(ShaderRef::new("/home/u/.config/hypr/shaders/blur.glsl"));
        l.open_anim = Some(ShaderRef {
            path: "/home/u/.config/hypr/shaders/open.glsl".into(),
            duration: Some(0.2),
        });
        c.layers.push(l);
        c.startup.push(StartupAction {
            id: "s1".into(),
            enabled: true,
            action: Action::ClassShader {
                class: "kitty".into(),
                shader: Some(ShaderRef::new("/home/u/.config/hypr/shaders/read.glsl")),
            },
        });

        let out = emit(&c).unwrap();
        let dispatched: Vec<&str> = out.lines().filter(|l| l.contains("hl.exec_cmd")).collect();
        assert_eq!(dispatched.len(), 1, "the calls go out in one exec_cmd");
        assert_eq!(dispatched[0].matches("hyprctl dispatch").count(), 3, "one per call");

        let line = dispatched[0];
        assert!(!line.contains(DIR_VAR), "{DIR_VAR} is nil inside hyprctl dispatch: {line}");
        // The paths are still there, just written in full.
        assert!(line.contains("/home/u/.config/hypr/shaders/blur.glsl"));
        assert!(line.contains("/home/u/.config/hypr/shaders/open.glsl@0.2"));
        assert!(line.contains("/home/u/.config/hypr/shaders/read.glsl"));
    }

    #[test]
    fn the_undelayed_handler_still_uses_the_directory_variable() {
        let mut c = cfg();
        let mut l = LayerEntry::new("l1", "rofi");
        l.shader = Some(ShaderRef::new("/home/u/.config/hypr/shaders/blur.glsl"));
        c.layers.push(l);

        let out = emit(&c).unwrap();
        assert!(out.contains(r#"hws.layershader("rofi", hws_shaders .. "/blur.glsl")"#));
        assert!(!out.contains("hyprctl dispatch"));
    }

    #[test]
    fn binds_look_the_plugin_up_inside_the_closure() {
        let mut c = cfg();
        c.binds.push(Bind {
            id: "b1".into(),
            enabled: true,
            key: "SUPER + W".into(),
            action: Action::ToggleWindowShader {
                shader: ShaderRef::new("/home/u/.config/hypr/shaders/pixelate.glsl"),
            },
        });
        let out = emit(&c).unwrap();
        assert!(out.contains(r#"hl.bind("SUPER + W", function()"#));
        assert!(out.contains("local hws = hl.plugin.HyprWindowShade"));
        assert!(out.contains(r#"hws.togglewindowshader(hws_shaders .. "/pixelate.glsl")"#));
    }

    #[test]
    fn a_startup_shader_also_uses_the_directory_variable() {
        let mut c = cfg();
        c.startup.push(StartupAction {
            id: "s1".into(),
            enabled: true,
            action: Action::ClassShader {
                class: "kitty".into(),
                shader: Some(ShaderRef::new("/home/u/.config/hypr/shaders/read.glsl")),
            },
        });
        let out = emit(&c).unwrap();
        assert!(out.contains(r#"hws.classshader("kitty", hws_shaders .. "/read.glsl")"#));
    }

    #[test]
    fn clear_is_emitted_for_an_empty_shader() {
        let mut c = cfg();
        c.startup.push(StartupAction {
            id: "s1".into(),
            enabled: true,
            action: Action::ClassShader { class: "kitty".into(), shader: None },
        });
        let out = emit(&c).unwrap();
        assert!(out.contains(r#"hws.classshader("kitty", "clear")"#));
    }

    #[test]
    fn hyprpm_loader_is_emitted_first() {
        let mut c = cfg();
        c.load_mode = LoadMode::Hyprpm;
        let out = emit(&c).unwrap();
        assert!(out.contains(r#"hl.exec_cmd("hyprpm reload -n")"#));
    }

    #[test]
    fn empty_config_emits_only_the_header() {
        let out = emit(&cfg()).unwrap();
        assert!(out.contains("hws-state-v1"));
        assert!(!out.contains("hl.window_rule"));
        assert!(!out.contains("hl.bind"));
    }

    #[test]
    fn shell_quoting_survives_an_apostrophe() {
        assert_eq!(shell_single_quote("it's"), r"'it'\''s'");
    }
}
